nodeLinker: node-modules

npmScopes:
  econ:
    npmRegistryServer: "https://gitlab.uzh.ch/api/v4/projects/662/packages/npm/"

packageExtensions:
  "@parcel/node-resolver-core@*":
    peerDependenciesMeta:
      "@parcel/core":
        optional: true
  "@parcel/types@*":
    peerDependenciesMeta:
      "@parcel/core":
        optional: true
