FROM ghcr.io/uzh/z-pool-tool/ocaml:9-5.3-2.3

# Set up environment
ENV SIHL_ENV=development

USER root

# NOTE: Pre-create volume folders for the correct ownership.
RUN mkdir -p /workspace/_build /workspace/node_modules /home/opam/.cache \
  && chown -R opam:opam /workspace/_build /workspace/node_modules /home/opam/.cache

# Install Node.js LTS
RUN wget -qO- https://rpm.nodesource.com/setup_lts.x | bash - \
  && dnf install -y nodejs \
  && dnf clean all \
  && npm install -g corepack \
  && corepack prepare yarn@3.8.7 --activate

USER opam

RUN touch /home/opam/.gitconfig_empty
