FROM ghcr.io/uzh/z-pool-tool/ocaml:9-5.3-2.3

# Set up environment
ENV SIHL_ENV=development

USER root

# NOTE: Pre-create volume folders for the correct ownership.
RUN mkdir -p /workspace/_build /workspace/node_modules \
  && chown -R opam:opam /workspace/_build /workspace/node_modules

# copy node from node container and link commands
COPY --from=node:lts /usr/local/lib/node_modules /usr/local/lib/node_modules
COPY --from=node:lts /usr/local/bin/node /usr/local/bin/node
COPY --from=node:lts /opt /opt
RUN ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm \
  && ln -s /usr/local/lib/node_modules/npm/bin/npx-cli.js /usr/local/bin/npx \
  && ln -s /usr/local/bin/node /usr/local/bin/nodejs \
  && ln -s /opt/yarn-v*/bin/yarn /usr/local/bin/yarn \
  && ln -s /opt/yarn-v*/bin/yarnpkg /usr/local/bin/yarnpkg

USER opam

RUN touch /home/opam/.gitconfig_empty
