let seed_default_message_templates =
  Database.Migration.Step.create
    ~label:"seed default message templates"
    {sql|
    INSERT INTO `pool_message_templates` (`uuid`, `label`, `language`, `email_subject`, `email_text_html`, `email_text_plain`, `sms_text`) VALUES
      (UNHEX(REPLACE(UUID(), '-', '')), 'account_suspension_notification', 'EN', 'Your account has been temporarily suspended', '<div><h4>Dear {name},</h4>\n <p>\n  due to too many failed login attempts, your account has been temporarily\n  suspended.\n </p>\n <p>If these attempts were not made by you, please inform an administrator.\n </p><p>Yours sincerely,<br/>{siteTitle}</p>\n</div>', 'Dear {name},\n\nDue to too many failed login attempts, your account has been temporarily suspended.\n\nIf these attempts were not made by you, please inform an administrator.\n\nYours sincerely,\n{siteTitle}', 'Dear {name},\n\nDue to too many failed login attempts, your account has been temporarily suspended.\n\nIf these attempts were not made by you, please inform an administrator.\n\nYours sincerely,\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'assignment_confirmation', 'EN', 'Assignment confirmation', '<div><h4>Dear {name},</h4>\n <p>You successfully registered to the following session/s:<br/>\n  {sessionOverview}\n </p><p>The participation in the session is compulsory.</p>\n <p>Yours sincerely,<br/>{siteTitle}</p>\n</div>', 'Dear {name},\n\nYou successfully registered to the following session/s:\n\n{sessionOverview}\n\nThe participation in the session is compulsory.\n\nYours sincerely,\n{siteTitle}', 'Dear {name},\n\nYou successfully registered to the following session/s:\n\n{sessionOverview}\n\nThe participation in the session is compulsory.\n\nYours sincerely,\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'contact_registration_attempt', 'EN', 'Signup attempt', '<div><h4>Dear {name},</h4>\n <p>\n  There was an attempt to create an account with the email address\n  \'{emailAddress}\' on {tenantUrl}.<br/>\n  An account with this email address already exists.\n </p>\n <p>\n  If this was you and you forgot your login credentials, you can reset your\n  password <a href=\"{resetUrl}\">here</a>.\n </p>\n <p>\n  If this action was not performed by you, you can ignore this message or\n  inform the administrators.\n </p>\n <p>\n  If the above link does not work, please copy the following link into your\n  browser manually: {resetUrl}\n </p><p>Yours sincerely,<br/>{siteTitle}</p>\n</div>', 'Dear {name},\n\nThere was an attempt to create an account with the email address \'{emailAddress}\' on {tenantUrl}.\n\nIf this was you and you forgot your login credentials, you can reset you can reset your password here: {resetUrl}\n\nIf this action was not performed by you, you can ignore this message or inform the administrators.\n\n\nYours sincerely,\n{siteTitle}', 'Dear {name},\n\nThere was an attempt to create an account with the email address \'{emailAddress}\' on {tenantUrl}.\n\nIf this was you and you forgot your login credentials, you can reset you can reset your password here: {resetUrl}\n\nIf this action was not performed by you, you can ignore this message or inform the administrators.\n\n\nYours sincerely,\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'email_verification', 'EN', 'Email verification', '<div><h4>Dear {name},</h4>\n <p>You recently added a new email address to your account.<br/>Follow this\n  <a href=\"{verificationUrl}\"> link </a>to activate it.\n </p>\n <p>\n  If this action wasn`t performed by you, please ignore this email or reply\n  to let us know.\n </p>\n <p>\n  If the above link does not work, please copy the following link into your\n  browser manually: {verificationUrl}\n </p><p>Yours sincerely,<br/>{siteTitle}</p>\n</div>', 'Dear {name},\n\nYou recently added a new email address to your account.\nFollow the link below to activate it.\n\n{verificationUrl}\n\nIf this action wasn`t performed by you, please ignore this email or reply to let us know.\n\nYours sincerely,\n{siteTitle}', 'Dear {name},\n\nYou recently added a new email address to your account.\nFollow the link below to activate it.\n\n{verificationUrl}\n\nIf this action wasn`t performed by you, please ignore this email or reply to let us know.\n\nYours sincerely,\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'experiment_invitation', 'EN', 'Experiment invitation', '<div><h4>Dear {name},</h4>\n <p>We would like to invite you to the following experiment:</p>\n <p><strong>{experimentPublicTitle}</strong></p>\n <p>{experimentDescription}</p>\n <p>Information about the sessions can be found \n  <a href=\"{experimentUrl}\">here</a>.\n </p>\n <p>\n  If the above link doesn\'t work, please copy the following link into your\n  browser manually: {experimentUrl}\n </p><p>Yours sincerely,<br/>{siteTitle}</p>\n</div>', 'Dear {name},\n\nWe would like to invite you to the following experiment:\n\n{experimentPublicTitle}\n{experimentDescription}\n\nInformation about the sessions can be found here: {experimentUrl}\n\nYours sincerely,\n{siteTitle}', 'Dear {name},\n\nWe would like to invite you to the following experiment:\n\n{experimentPublicTitle}\n{experimentDescription}\n\nInformation about the sessions can be found here: {experimentUrl}\n\nYours sincerely,\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'password_change', 'EN', 'Password change', '<div><h4>Dear {name},</h4>\n <p>You recently changed your password for your account.</p>\n <p>If you did not change your password, please get in contact with us.</p>\n <p>Yours sincerely,<br/>{siteTitle}</p>\n</div>', 'Dear {name},\n\nYou recently changed your password for your account.\n\nIf you did not change your password, please get in contact with us.\n\nYours sincerely,\n{siteTitle}', 'Dear {name},\n\nYou recently changed your password for your account.\n\nIf you did not change your password, please get in contact with us.\n\nYours sincerely,\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'password_reset', 'EN', 'Password reset', '<div><h4>Dear {name},</h4>\n <p>You recently requested to reset your password for your account.<br/>\n  Follow this<a href=\"{resetUrl}\"> link </a>to reset it.\n </p>\n <p>\n  If you did not request a password reset, please ignore this email or reply\n  to let us know. This password reset is only valid for the next hour.\n </p>\n <p>\n  If the above link doesn\'t work, please copy the following link into your\n  browser manually: {resetUrl}\n </p><p>Yours sincerely,<br/>{siteTitle}</p>\n</div>', 'Dear {name},\n\nYou recently requested to reset your password for your account.\nFollow the link below to reset it.\n\n{resetUrl}\n\nIf you did not request a password reset, please ignore this email or\nreply to let us know. This password reset is only valid for the next\nhour.\n\nYours sincerely,\n{siteTitle}', 'Dear {name},\n\nYou recently requested to reset your password for your account.\nFollow the link below to reset it.\n\n{resetUrl}\n\nIf you did not request a password reset, please ignore this email or\nreply to let us know. This password reset is only valid for the next\nhour.\n\nYours sincerely,\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'phone_verification', 'EN', 'Phone verification', 'Your phone number verification code: {token}', 'Your phone number verification code: {token}', 'Your phone number verification code: {token}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'profile_update_trigger', 'EN', 'Please check your profile.', '<div><h4>Dear {name},</h4>\n <p>Your profile has not been updated in a while.</p>\n <p>Please check your <a href=\"{profileUrl}\"> profile</a>.</p>\n <p>Yours sincerely,<br/>{siteTitle}</p>\n</div>', 'Dear {name},\n\nYour profile has not been updated in a while.\n\nPlease check your profile: {profileUrl}\n\nYours sincerely,\n{siteTitle}', 'Dear {name},\n\nYour profile has not been updated in a while.\n\nPlease check your profile: {profileUrl}\n\nYours sincerely,\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'session_cancellation', 'EN', 'Session cancellation', '<div><h4>Dear {name},</h4>\n <p>The following session you have registered to was canceled:</p>\n <p>{sessionOverview}</p><p>Reason:</p><p>{reason}</p>\n <p>Yours sincerely,<br/>{siteTitle}</p>\n</div>', 'Dear {name},\n\nThe following session you have registered to was canceled:\n\n{sessionOverview}\n\nReason: {reason}\n\nYours sincerely,\n{siteTitle}', 'Dear {name},\n\nThe following session you have registered to was canceled:\n\n{sessionOverview}\n\nReason: {reason}\n\nYours sincerely,\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'session_reminder', 'EN', 'Session reminder', '<div><h4>Dear {name},</h4>\n <p>Herewith we remind you about your upcoming experiment session:<br/>\n  {sessionOverview}\n </p><p>Yours sincerely,<br/>{siteTitle}</p>\n</div>', 'Dear {name},\n\nHerewith we remind you about your upcoming experiment session:\n\n{sessionOverview}\n\nYours sincerely,\n{siteTitle}', 'Dear {name},\n\nHerewith we remind you about your upcoming experiment session:\n\n{sessionOverview}\n\nYours sincerely,\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'session_reschedule', 'EN', 'Session was rescheduled', '<div><h4>Dear {name},</h4>\n <p>The following session you have registered to was rescheduled:<br/>\n  {sessionOverview}\n </p><p>The new date and time is:<br/>{newStart}<br/>{newDuration}</p>\n <p>Yours sincerely,<br/>{siteTitle}</p>\n</div>', 'Dear {name},\n\nThe following session you have registered to was rescheduled\n\n{sessionOverview}\n\nNew:\n{newStart}\n{newDuration}\n\n\nYours sincerely,\n{siteTitle}', 'Dear {name},\n\nThe following session you have registered to was rescheduled\n\n{sessionOverview}\n\nNew:\n{newStart}\n{newDuration}\n\n\nYours sincerely,\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'signup_verification', 'EN', 'Sign up verification', '<div><h4>Dear {name},</h4>\n <p>Thank your for signing up for the Pool Tool.<br/>Follow this\n  <a href=\"{verificationUrl}\"> link </a>to activate your account.\n </p>\n <p>\n  If this action wasn`t performed by you, please ignore this email or reply\n  to let us know.\n </p>\n <p>\n  If the above link does not work, please copy the following link into your\n  browser manually: {verificationUrl}\n </p><p>Yours sincerely,<br/>{siteTitle}</p>\n</div>', 'Dear {name},\n\nThank your for signing up for the Pool Tool.\nFollow the link below to activate your account.\n\n{verificationUrl}\n\nIf this action wasn`t performed by you, please ignore this email or reply to let us know.\n\nYours sincerely,\n{siteTitle}', 'Dear {name},\n\nThank your for signing up for the Pool Tool.\nFollow the link below to activate your account.\n\n{verificationUrl}\n\nIf this action wasn`t performed by you, please ignore this email or reply to let us know.\n\nYours sincerely,\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'user_import', 'EN', 'Reactivation of your account', '<div><h4>Dear {name},</h4>\n <p>Your account was recently migrated.<br/>Follow this \n  <a href=\"{confirmationUrl}\">link</a> to reactivate your account.\n </p>\n <p>\n  If the above link does not work, please copy the manually into your\n  browser: {confirmationUrl}\n </p><p>Yours sincerely,<br/>{siteTitle}</p>\n</div>', 'Dear {name},\n\nYour account was recently migrated. Follow this link to reactivate your account:\n\n{confirmationUrl}\n\nYours sincerely,\n{siteTitle}', 'Dear {name},\n\nYour account was recently migrated. Follow this link to reactivate your account:\n\n{confirmationUrl}\n\nYours sincerely,\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'account_suspension_notification', 'DE', 'Ihr Account wurde temporär gesperrt', '<div><h4>Liebe*r {name},</h4>\n <p>\n  aufgrund zu vieler fehlgeschlagener Anmeldeversuche wurde Ihr Account\n  vorübergehend gesperrt.\n </p>\n <p>\n  Wenn diese Versuche nicht von Ihnen durchgeführt wurden, informieren Sie\n  bitte einen Administrator.\n </p><p>Freundliche Grüsse<br/>{siteTitle}</p>\n</div>', 'Liebe*r {name},\n\nAufgrund zu vieler fehlgeschlagener Anmeldeversuche wurde Ihr Account vorübergehend gesperrt.\n\nWenn diese Versuche nicht von Ihnen durchgeführt wurden, informieren Sie bitte einen Administrator.\n\nFreundliche Grüsse\n{siteTitle}', 'Liebe*r {name},\n\nAufgrund zu vieler fehlgeschlagener Anmeldeversuche wurde Ihr Account vorübergehend gesperrt.\n\nWenn diese Versuche nicht von Ihnen durchgeführt wurden, informieren Sie bitte einen Administrator.\n\nFreundliche Grüsse\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'assignment_confirmation', 'DE', 'Registrierungsbestätigung', '<div><h4>Liebe*r {name},</h4>\n <p>\n  Sie wurden erfolgreich zur folgenden Session / zu den folgenden Sessions\n  angemeldet:<br/>{sessionOverview}\n </p><p>Die Teilnahme ist obligatorisch.</p>\n <p>Freundliche Grüsse<br/>{siteTitle}</p>\n</div>', 'Liebe*r {name},\n\nSie wurden erfolgreich zur folgenden Session / zu den folgenden Sessions angemeldet:\n\n{sessionOverview}\n\nDie Teilnahme ist obligatorisch.\n\nFreundliche Grüsse\n{siteTitle}', 'Liebe*r {name},\n\nSie wurden erfolgreich zur folgenden Session / zu den folgenden Sessions angemeldet:\n\n{sessionOverview}\n\nDie Teilnahme ist obligatorisch.\n\nFreundliche Grüsse\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'contact_registration_attempt', 'DE', 'Registrierungsversuch', '<div><h4>Liebe*r {name},</h4>\n <p>\n  Es wurde versucht, auf {tenantUrl} ein Konto mit der E-Mail-Adresse\n  \'{emailAddress}\' zu erstellen.<br/>\n  Es existiert bereits ein Konto mit dieser E-Mail-Adresse.\n </p>\n <p>\n  Wenn Sie dies waren und Ihre Anmeldedaten vergessen haben, können Sie Ihr\n  Passwort <a href=\"{resetUrl}\">hier</a>zurücksetzen.\n </p>\n <p>\n  Wenn diese Aktion nicht von Ihnen durchgeführt wurde, können Sie diese\n  Meldung ignorieren oder die Administratoren informieren.\n </p>\n <p>\n  Wenn der obige Link nicht funktioniert, kopieren Sie bitte den folgenden\n  Link manuell in Ihren Browser: {resetUrl}\n </p><p>Freundliche Grüsse<br/>{siteTitle}</p>\n</div>', 'Liebe*r {name},\n\nEs wurde versucht, ein Konto mit der E-Mail-Adresse \'{emailAddress}\' auf {tenantUrl} zu erstellen.\n\n    Wenn dies Sie waren und Sie Ihre Anmeldedaten vergessen haben, können Sie Ihr Passwort hier zurücksetzen: {resetUrl}\n\n    Wenn diese Aktion nicht von Ihnen durchgeführt wurde, können Sie diese Meldung ignorieren oder die Administratoren informieren.\n\n\nFreundliche Grüsse\n{siteTitle}', 'Liebe*r {name},\n\nEs wurde versucht, ein Konto mit der E-Mail-Adresse \'{emailAddress}\' auf {tenantUrl} zu erstellen.\n\n    Wenn dies Sie waren und Sie Ihre Anmeldedaten vergessen haben, können Sie Ihr Passwort hier zurücksetzen: {resetUrl}\n\n    Wenn diese Aktion nicht von Ihnen durchgeführt wurde, können Sie diese Meldung ignorieren oder die Administratoren informieren.\n\n\nFreundliche Grüsse\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'email_verification', 'DE', 'Neue E-Mail-Adresse', '<div><h4>Liebe*r {name},</h4>\n <p>\n  Du hast kürzlich eine neue E-Mail-Adresse zu deinem Account hinzugefügt.\n  <br/>Nutze diesen<a href=\"{verificationUrl}\"> Link </a>\n  um sie zu aktivieren.\n </p>\n <p>\n  Wenn du diese Aktion nicht ausgeführt hattest, dann ignoriere diese E-Mail\n  oder trete mit uns in Kontakt.\n </p>\n <p>\n  Falls der obige Link nicht funktioniert, kopiere bitte den folgenden\n  manuell in deinen Browser: {verificationUrl}\n </p><p>Freundliche Grüsse<br/>{siteTitle}</p>\n</div>', 'Liebe*r {name},\n\nDu hast kürzlich eine neue E-Mail-Adresse zu deinem Account hinzugefügt.\n\n{verificationUrl}\n\nWenn Sie diese Aktion nicht ausgeführt haben, dann ignorieren Sie diese E-Mail oder trete mit uns in Kontakt.\n\nFreundliche Grüsse\n{siteTitle}', 'Liebe*r {name},\n\nDu hast kürzlich eine neue E-Mail-Adresse zu deinem Account hinzugefügt.\n\n{verificationUrl}\n\nWenn Sie diese Aktion nicht ausgeführt haben, dann ignorieren Sie diese E-Mail oder trete mit uns in Kontakt.\n\nFreundliche Grüsse\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'experiment_invitation', 'DE', 'Einladung zu einem Experiment', '<div><h4>Liebe*r {name},</h4>\n <p>Wir möchten Sie zu einem bevorstehenden Experiment einladen:</p>\n <p><strong>{experimentPublicTitle}</strong></p>\n <p>{experimentDescription}</p>\n <p>Informationen zu den Sessions finden Sie \n  <a href=\"{experimentUrl}\">hier</a>.\n </p>\n <p>\n  Falls der obige Link nicht funktioniert, kopiere bitte den folgenden\n  manuell in deinen Browser: {experimentUrl}\n </p><p>Freundliche Grüsse<br/>{siteTitle}</p>\n</div>', 'Liebe*r {name},\n\nWir möchten Sie zu einem bevorstehenden Experiment einladen:\n\n{experimentPublicTitle}\n{experimentDescription}\n\nInformationen zu den Sessions finden Sie hier: {experimentUrl}\n\nFreundliche Grüsse\n{siteTitle}', 'Liebe*r {name},\n\nWir möchten Sie zu einem bevorstehenden Experiment einladen:\n\n{experimentPublicTitle}\n{experimentDescription}\n\nInformationen zu den Sessions finden Sie hier: {experimentUrl}\n\nFreundliche Grüsse\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'password_change', 'DE', 'Neues Passwort', '<div><h4>Liebe*r {name},</h4>\n <p>Du hast kürzlich das Passwort deines Accounts geändert.</p>\n <p>\n  Wenn du dein Passwort nicht geändert hast, dann kontaktiere uns bitte\n  umgehend.\n </p><p>Freundliche Grüsse<br/>{siteTitle}</p>\n</div>', 'Liebe*r {name},\n\nDu hast kürzlich das Passwort deines Accounts geändert.\n\nWenn du dein Passwort nicht geändert hast, dann kontaktiere uns bitte umgehend.\n\nFreundliche Grüsse\n{siteTitle}', 'Liebe*r {name},\n\nDu hast kürzlich das Passwort deines Accounts geändert.\n\nWenn du dein Passwort nicht geändert hast, dann kontaktiere uns bitte umgehend.\n\nFreundliche Grüsse\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'password_reset', 'DE', 'Passwort zurückgesetzt', '<div><h4>Liebe*r {name},</h4>\n <p>\n  Du hast kürzlich beantragt, dein Passwort für deinen Account\n  zurückzusetzen.<br/>Nutze diesen<a href=\"{resetUrl}\"> Link </a>\n  um es zurückzusetzen.\n </p>\n <p>\n  Wenn du dies nicht beantragt hast, kannst du diese E-Mail ignorieren oder\n  mit und Kontakt aufnehmen. Der Link ist für die nächste Stunde valid,\n  anschliessend muss ein neuer beantragt werden.\n </p>\n <p>\n  Falls der obige Link nicht funktioniert, kopiere bitte den folgenden\n  manuell in deinen Browser: {resetUrl}\n </p><p>Freundliche Grüsse<br/>{siteTitle}</p>\n</div>', 'Liebe*r {name},\n\nDu hast kürzlich beantragt, dein Passwort für deinen Account zurückzusetzen.\n\n{resetUrl}\n\nWenn du dies nicht beantragt hast, kannst du diese E-Mail ignorieren oder mit und Kontakt aufnehmen. Der Link ist für die nächste Stunde gültig, anschliessend muss ein neuer beantragt werden.\n\nFreundliche Grüsse\n{siteTitle}', 'Liebe*r {name},\n\nDu hast kürzlich beantragt, dein Passwort für deinen Account zurückzusetzen.\n\n{resetUrl}\n\nWenn du dies nicht beantragt hast, kannst du diese E-Mail ignorieren oder mit und Kontakt aufnehmen. Der Link ist für die nächste Stunde gültig, anschliessend muss ein neuer beantragt werden.\n\nFreundliche Grüsse\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'phone_verification', 'DE', 'Verifizierung Mobiltelefonnummer', 'Ihr Code zur Verifizierung Ihrer Mobiltelefonnummer: {token}', 'Ihr Code zur Verifizierung Ihrer Mobiltelefonnummer: {token}', 'Ihr Code zur Verifizierung Ihrer Mobiltelefonnummer: {token}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'profile_update_trigger', 'DE', 'Bitte kontrollieren Sie Ihr Profil.', '<div><h4>Liebe*r {name},</h4>\n <p>Ihr Profil wurde schon länger nicht aktualisiert.</p>\n <p>Bitte kotrollieren Sie die Angaben in Ihrem \n  <a href=\"{profileUrl}\"> Profil </a>.\n </p><p>Freundliche Grüsse<br/>{siteTitle}</p>\n</div>', 'Liebe*r {name},\n\nIhr Profil wurde schon länger nicht aktualisiert.\n\nBitte kontrollieren Sie die Angaben in Ihrem Profil: {profileUrl}\n\nFreundliche Grüsse\n{siteTitle}', 'Liebe*r {name},\n\nIhr Profil wurde schon länger nicht aktualisiert.\n\nBitte kontrollieren Sie die Angaben in Ihrem Profil: {profileUrl}\n\nFreundliche Grüsse\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'session_cancellation', 'DE', 'Session abgesagt', '<div><h4>Liebe*r {name},</h4>\n <p>Die folgende Session, zu der du angemeldet warst, wurde abgesagt:</p>\n <p>{sessionOverview}</p><p>Grund:</p><p>{reason}</p>\n <p>Freundliche Grüsse<br/>{siteTitle}</p>\n</div>', 'Liebe*r {name},\n\nDie folgende Session, zu der du angemeldet warst, wurde abgesagt:\n\n{sessionOverview}\n\nGrund: {reason}\n\n\nFreundliche Grüsse\n{siteTitle}', 'Liebe*r {name},\n\nDie folgende Session, zu der du angemeldet warst, wurde abgesagt:\n\n{sessionOverview}\n\nGrund: {reason}\n\n\nFreundliche Grüsse\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'session_reminder', 'DE', 'Session reminder', '<div><h4>Liebe*r {name},</h4>\n <p>Hiermit erinnern wir Sie an die Experiment-Session:<br/>{sessionOverview}\n </p><p>Freundliche Grüsse<br/>{siteTitle}</p>\n</div>', 'Liebe*r {name},\n\nHiermit erinnern wir Sie an die Experiment-Session\n\n{sessionOverview}\n\nFreundliche Grüsse\n{siteTitle}', 'Liebe*r {name},\n\nHiermit erinnern wir Sie an die Experiment-Session\n\n{sessionOverview}\n\nFreundliche Grüsse\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'session_reschedule', 'DE', 'Eine Session wurde verschoben', '<div><h4>Liebe*r {name},</h4>\n <p>Eine Session, zu der Sie angemeldet sind, wurde verschoben:<br/>\n  {sessionOverview}\n </p><p>Der neue Zeitpunkt ist:<br/>{newStart}<br/>{newDuration}</p>\n <p>Freundliche Grüsse<br/>{siteTitle}</p>\n</div>', 'Liebe*r {name},\n\nEine Session, zu der Sie angemeldet sind, wurde verschoben:\n\n{sessionOverview}\n\nNeu:\n{newStart}\n{newDuration}\n\n\nFreundliche Grüsse\n{siteTitle}', 'Liebe*r {name},\n\nEine Session, zu der Sie angemeldet sind, wurde verschoben:\n\n{sessionOverview}\n\nNeu:\n{newStart}\n{newDuration}\n\n\nFreundliche Grüsse\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'signup_verification', 'DE', 'Registrierungsbestätigung', '<div><h4>Liebe*r {name},</h4>\n <p>Vielen Dank für deine Anmeldung beim Pool Tool.<br/>Nutze diesen\n  <a href=\"{verificationUrl}\"> Link </a>um deinen Account zu aktivieren.\n </p>\n <p>\n  Wenn du dies nicht beantragt hast, kannst du diese E-Mail ignorieren oder\n  mit und Kontakt aufnehmen.\n </p>\n <p>\n  Falls der obige Link nicht funktioniert, kopiere bitte den folgenden\n  manuell in deinen Browser: {verificationUrl}\n </p><p>Freundliche Grüsse<br/>{siteTitle}</p>\n</div>', 'Liebe*r {name},\n\nVielen Dank für deine Anmeldung beim Pool Tool.\nNutze den folgenden Link um deinen Account zu aktivieren.\n\n{verificationUrl}\n\nWenn du dies nicht beantragt hast, kannst du diese E-Mail ignorieren oder mit und Kontakt aufnehmen.\n\nFreundliche Grüsse\n{siteTitle}', 'Liebe*r {name},\n\nVielen Dank für deine Anmeldung beim Pool Tool.\nNutze den folgenden Link um deinen Account zu aktivieren.\n\n{verificationUrl}\n\nWenn du dies nicht beantragt hast, kannst du diese E-Mail ignorieren oder mit und Kontakt aufnehmen.\n\nFreundliche Grüsse\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'user_import', 'DE', 'Reaktivierung Ihres Accounts', '<div><h4>Liebe*r {name},</h4>\n <p>Ihr Account wurde kürzlich migriert.<br/>Nutzen Sie diesen\n  <a href=\"{confirmationUrl}\"> Link </a>\n  um Ihren Account wieder zu aktivieren.\n </p>\n <p>\n  Falls der obige Link nicht funktioniert, kopiere bitte den folgenden\n  manuell in deinen Browser: {confirmationUrl}\n </p><p>Freundliche Grüsse<br/>{siteTitle}</p>\n</div>', 'Liebe*r {name},\n\nIhr Account wurde kürzlich migriert. Nutzen Sie den folgenden Link um Ihren Account wieder zu aktivieren:\n\n{confirmationUrl}\n\nFreundliche Grüsse\n{siteTitle}', 'Liebe*r {name},\n\nIhr Account wurde kürzlich migriert. Nutzen Sie den folgenden Link um Ihren Account wieder zu aktivieren:\n\n{confirmationUrl}\n\nFreundliche Grüsse\n{siteTitle}');
  |sql}
;;

let seed_waiting_list_confirmation =
  Database.Migration.Step.create
    ~label:"seed waiting list confirmation"
    {sql|
    INSERT INTO `pool_message_templates` (`uuid`, `label`, `language`, `email_subject`, `email_text_html`, `email_text_plain`, `sms_text`) VALUES
      (UNHEX(REPLACE(UUID(), '-', '')), 'waiting_list_confirmation', 'EN', 'Waiting list enrollment confirmation', '<div><h4>Dear {name},</h4>\n <p>\n  You have successfully enrolled to the waiting list of the experiment\n  {experimentPublicTitle}.<br/>\n  The recruitment team will get in touch with you.\n </p><p>Yours sincerely,<br/>{siteTitle}</p>\n</div>', 'Dear {name},\n\nYou have successfully enrolled to the waiting list of the experiment {experimentPublicTitle}.\n\n    The recruitment team will get in touch with you.\n\nYours sincerely,\n{siteTitle}', 'Dear {name},\n\nYou have successfully enrolled to the waiting list of the experiment {experimentPublicTitle}.\n\n    The recruitment team will get in touch with you.\n\nYours sincerely,\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'waiting_list_confirmation', 'DE', 'Anmeldung Warteliste', '<div><h4>Liebe*r {name},</h4>\n <p>\n  Sie haben sich erfolgreich auf die Warteliste für das Experiment\n  {experimentPublicTitle} gesetzt.<br/>\n  Das Recruitment Team wird sich mit Ihnen in Verbindung setzen.\n </p><p>Freundliche Grüsse<br/>{siteTitle}</p>\n</div>', 'Liebe*r {name},\n\nSie haben sich erfolgreich auf die Warteliste für das Experiment {experimentPublicTitle} gesetzt.\n\n    Das Recruitment Team wird sich mit Ihnen in Verbindung setzen.\n\nFreundliche Grüsse\n{siteTitle}', 'Liebe*r {name},\n\nSie haben sich erfolgreich auf die Warteliste für das Experiment {experimentPublicTitle} gesetzt.\n\n    Das Recruitment Team wird sich mit Ihnen in Verbindung setzen.\n\nFreundliche Grüsse\n{siteTitle}')
  |sql}
;;

let seed_assignment_session_change_notification =
  Database.Migration.Step.create
    ~label:"seed waiting list confirmation"
    {sql|
    INSERT INTO `pool_message_templates` (`uuid`, `label`, `language`, `email_subject`, `email_text_html`, `email_text_plain`, `sms_text`) VALUES
      (UNHEX(REPLACE(UUID(), '-', '')), 'assignment_session_change', 'EN', 'You have been assigned to a new session', '<div><h4>Dear {name},</h4>\n <p>You have been assigned to a new session:<br/>{sessionOverview}</p>\n <p>You are no longer signed up for the session on {oldSessionStart}.</p>\n <p>Yours sincerely,<br/>{siteTitle}</p>\n</div>', 'Dear {name},\n\nYou have been assigned to a new session:\n\n{sessionOverview}\n\nYou are no longer signed up for the session on {oldSessionStart}.\n\nYours sincerely,\n{siteTitle}', 'Dear {name},\n\nYou have been assigned to a new session:\n\n{sessionOverview}\n\nYou are no longer signed up for the session on {oldSessionStart}.\n\nYours sincerely,\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'assignment_session_change', 'DE', 'Sie wurden einer neuen Session zugewiesen', '<div><h4>Liebe*r {name},</h4>\n <p>Sie wurden einer neuen Session zugewiesen:<br/>{sessionOverview}</p>\n <p>An der Session vom {oldSessionStart} sind Sie nicht mehr angemeldet.</p>\n <p>Freundliche Grüsse<br/>{siteTitle}</p>\n</div>', 'Liebe*r {name},\n\nSie wurden einer neuen Session zugewiesen:\n\n{sessionOverview}\n\nAn der Session vom {oldSessionStart} sind Sie nicht mehr angemeldet.\n\nFreundliche Grüsse\n{siteTitle}', 'Liebe*r {name},\n\nSie wurden einer neuen Session zugewiesen:\n\n{sessionOverview}\n\nAn der Session vom {oldSessionStart} sind Sie nicht mehr angemeldet.\n\nFreundliche Grüsse\n{siteTitle}')
  |sql}
;;

let add_i18n_unique_constraint =
  Database.Migration.Step.create
    ~label:"add i18n unique constraint"
    {sql|
      ALTER TABLE pool_i18n
        ADD CONSTRAINT unique_key_language_combination UNIQUE (i18n_key, language);
    |sql}
;;

let seed_default_i18n =
  Database.Migration.Step.create
    ~label:"seed default i18n data"
    {sql|
    INSERT INTO `pool_i18n` (`uuid`, `i18n_key`, `language`, `content`) VALUES
      (UNHEX(REPLACE(UUID(), '-', '')), 'credits_text', 'EN', '<h2>Credits</h2>'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'credits_text', 'DE', '<h2>Impressum</h2>'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'greetings_text', 'EN', 'Greetings Text '),
      (UNHEX(REPLACE(UUID(), '-', '')), 'greetings_text', 'DE', 'Begrüssungstext'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'welcome_text', 'EN', 'We conduct economic studies in our labs on a regular basis. Most of these take place in a computer lab where participants sit at a computer and answer questions or take decisions on given situations. In addition to our computer lab studies, we also run studies using technological devices, such as fMRI scanners, etc.\n\nOnce you are registered in our database and your account is activated, you will receive invitation emails with information on current studies. After receiving an invitation email, you can decide for yourself whether you would like to participate in a study or not. Your data is treated anonymously and we use your data only for study purposes. In order to participate you must be at least 18 years old.\n\nWe look forward to welcoming you soon to one of our upcoming studies.\n'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'welcome_text', 'DE', 'Wir führen regelmässig wirtschaftswissenschaftliche Studien durch. Meist finden die Studien in einem Computerlabor statt, wo Sie an einem Computer sitzen und Fragen beantworten oder Entscheidungen zu gegebenen Situationen treffen. Darüberhinaus führen wir auch Studien mit anderen technischen Hilfsmitteln (bsp. FMRI, EEG) durch.\n\nWenn Sie sich bei uns registrieren und Ihr Account freigeschaltet wurde, erhalten Sie Einladungsemails mit Informationen zu aktuellen Studien. Nun können Sie selbst bestimmen, ob Sie gerne bei der betreffenden Studie mitmachen wollen. Die Studien werden anonym durchgeführt und nur für die wissenschaftliche Forschungsarbeit genutzt. Um an unseren Studien teilzunehmen, müssen Sie mindestens 18 Jahre alt sein.\n\nWir freuen uns Sie bald bei einer unserer Studien begrüssen zu dürfen.\n'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'password_policy_text', 'EN', 'The password must be at least 8 characters long, contain a number, a capital letter and a special character.'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'password_policy_text', 'DE', 'Das Passwort muss mindestens 8 Zeichen lang sein, eine Zahl, ein Grossbuchstabe und ein Sonderzeichen enthalten.'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'privacy_policy', 'EN', '<h1>Privacy policy</h1>'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'privacy_policy', 'DE', '<h1>Datenschutzerklärung</h1>')
      ON DUPLICATE KEY UPDATE id = id;
  |sql}
;;

let seed_default_system_settings =
  Database.Migration.Step.create
    ~label:"seed default system settings"
    {sql|
      INSERT INTO pool_system_settings (uuid, settings_key, value) VALUES
        (UNHEX(REPLACE(UUID(), '-', '')), '[\"default_reminder_lead_time\"]', '28800'),
        (UNHEX(REPLACE(UUID(), '-', '')), '[\"default_text_msg_reminder_lead_time\"]', '14400'),
        (UNHEX(REPLACE(UUID(), '-', '')), '[\"languages\"]', '[[\"EN\"],[\"DE\"]]'),
        (UNHEX(REPLACE(UUID(), '-', '')), '[\"email_suffixes\"]', '[]'),
        (UNHEX(REPLACE(UUID(), '-', '')), '[\"contact_email\"]', '\"pool@email.com\"'),
        (UNHEX(REPLACE(UUID(), '-', '')), '[\"inactive_user_disable_after\"]', '5'),
        (UNHEX(REPLACE(UUID(), '-', '')), '[\"inactive_user_warning\"]', '7'),
        (UNHEX(REPLACE(UUID(), '-', '')), '[\"trigger_profile_update_after\"]', '365'),
        (UNHEX(REPLACE(UUID(), '-', '')), '[\"terms_and_conditions\"]', '[[[\"EN\"],\"<p>Terms and conditions</p>"],[[\"DE\"],\"<p>Nutzungsbedingungen</p>"]]')
      ON DUPLICATE KEY UPDATE id = id;
  |sql}
;;

let migration () =
  Database.Migration.(
    empty "202309261013"
    |> add_step seed_default_message_templates
    |> add_step seed_waiting_list_confirmation
    |> add_step seed_assignment_session_change_notification
    |> add_step add_i18n_unique_constraint
    |> add_step seed_default_i18n
    |> add_step seed_default_system_settings)
;;

let seed_root_default_message_templates_workiing =
  Database.Migration.Step.create
    ~label:"seed default message templates"
    {sql|
    INSERT INTO `pool_message_templates` (`uuid`, `label`, `language`, `email_subject`, `email_text_html`, `email_text_plain`, `sms_text`) VALUES
      (UNHEX(REPLACE(UUID(), '-', '')), 'password_reset', 'EN', 'Password reset', 'html', 'Dear {name},\n\nYou recently requested to reset your password for your account.\nFollow the link below to reset it.\n\n{resetUrl}\n\nIf you did not request a password reset, please ignore this email or\nreply to let us know. This password reset is only valid for the next\nhour.\n\nYours sincerely,\n{siteTitle}', 'Dear {name},\n\nYou recently requested to reset your password for your account.\nFollow the link below to reset it.\n\n{resetUrl}\n\nIf you did not request a password reset, please ignore this email or\nreply to let us know. This password reset is only valid for the next\nhour.\n\nYours sincerely,\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'password_reset', 'DE', 'Passwort zurückgesetzt', 'html', 'Liebe*r {name},\n\nDu hast kürzlich beantragt, dein Passwort für deinen Account zurückzusetzen.\n\n{resetUrl}\n\nWenn du dies nicht beantragt hast, kannst du diese E-Mail ignorieren oder mit und Kontakt aufnehmen. Der Link ist für die nächste Stunde gültig, anschliessend muss ein neuer beantragt werden.\n\nFreundliche Grüsse\n{siteTitle}', 'Liebe*r {name},\n\nDu hast kürzlich beantragt, dein Passwort für deinen Account zurückzusetzen.\n\n{resetUrl}\n\nWenn du dies nicht beantragt hast, kannst du diese E-Mail ignorieren oder mit und Kontakt aufnehmen. Der Link ist für die nächste Stunde gültig, anschliessend muss ein neuer beantragt werden.\n\nFreundliche Grüsse\n{siteTitle}');
    |sql}
;;

let seed_root_default_message_templates =
  Database.Migration.Step.create
    ~label:"seed root default message templates"
    {sql|
    INSERT INTO `pool_message_templates` (`uuid`, `label`, `language`, `email_subject`, `email_text_html`, `email_text_plain`, `sms_text`) VALUES
      (UNHEX(REPLACE(UUID(), '-', '')), 'password_reset', 'EN', 'Password reset', '<div><h4>Dear {name},</h4><p>You recently requested to reset your password for your account.<br/> Follow this<a href=\"{resetUrl}\"> link </a>to reset it.</p><p>If you did not request a password reset, please ignore this email or reply to let us know. This password reset is only valid for the next hour.</p><p>If the above link does not work, please copy the following link into your browser manually: {resetUrl}</p><p>Yours sincerely,<br/>{siteTitle}</p></div>', 'Dear {name},\n\nYou recently requested to reset your password for your account.\nFollow the link below to reset it.\n\n{resetUrl}\n\nIf you did not request a password reset, please ignore this email or\nreply to let us know. This password reset is only valid for the next\nhour.\n\nYours sincerely,\n{siteTitle}', 'Dear {name},\n\nYou recently requested to reset your password for your account.\nFollow the link below to reset it.\n\n{resetUrl}\n\nIf you did not request a password reset, please ignore this email or\nreply to let us know. This password reset is only valid for the next\nhour.\n\nYours sincerely,\n{siteTitle}'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'password_reset', 'DE', 'Passwort zurückgesetzt', '<div><h4>Liebe*r {name},</h4><p>Du hast kürzlich beantragt, dein Passwort für deinen Account zurückzusetzen.<br/>Nutze diesen<a href=\"{resetUrl}\"> Link </a> um es zurückzusetzen.</p><p> Wenn du dies nicht beantragt hast, kannst du diese E-Mail ignorieren oder mit und Kontakt aufnehmen. Der Link ist für die nächste Stunde valid, anschliessend muss ein neuer beantragt werden.</p><p>Falls der obige Link nicht funktioniert, kopiere bitte den folgenden manuell in deinen Browser: {resetUrl}</p><p>Freundliche Grüsse<br/>{siteTitle}</p></div>', 'Liebe*r {name},\n\nDu hast kürzlich beantragt, dein Passwort für deinen Account zurückzusetzen.\n\n{resetUrl}\n\nWenn du dies nicht beantragt hast, kannst du diese E-Mail ignorieren oder mit und Kontakt aufnehmen. Der Link ist für die nächste Stunde gültig, anschliessend muss ein neuer beantragt werden.\n\nFreundliche Grüsse\n{siteTitle}', 'Liebe*r {name},\n\nDu hast kürzlich beantragt, dein Passwort für deinen Account zurückzusetzen.\n\n{resetUrl}\n\nWenn du dies nicht beantragt hast, kannst du diese E-Mail ignorieren oder mit und Kontakt aufnehmen. Der Link ist für die nächste Stunde gültig, anschliessend muss ein neuer beantragt werden.\n\nFreundliche Grüsse\n{siteTitle}');
    |sql}
;;

let add_root_i18n_unique_constraint =
  Database.Migration.Step.create
    ~label:"add root i18n unique constraint"
    {sql|
      ALTER TABLE pool_i18n
        ADD CONSTRAINT unique_key_language_combination UNIQUE (i18n_key, language);
    |sql}
;;

let seed_root_default_i18n =
  Database.Migration.Step.create
    ~label:"seed root default i18n data"
    {sql|
    INSERT INTO pool_i18n (uuid, i18n_key, language, content) VALUES
      (UNHEX(REPLACE(UUID(), '-', '')), 'credits_text', 'EN', '<h2>Credits</h2>'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'credits_text', 'DE', '<h2>Impressum</h2>'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'greetings_text', 'EN', 'Greetings Text '),
      (UNHEX(REPLACE(UUID(), '-', '')), 'greetings_text', 'DE', 'Begrüssungstext'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'welcome_text', 'EN', 'We conduct economic studies in our labs on a regular basis. Most of these take place in a computer lab where participants sit at a computer and answer questions or take decisions on given situations. In addition to our computer lab studies, we also run studies using technological devices, such as fMRI scanners, etc.\n\nOnce you are registered in our database and your account is activated, you will receive invitation emails with information on current studies. After receiving an invitation email, you can decide for yourself whether you would like to participate in a study or not. Your data is treated anonymously and we use your data only for study purposes. In order to participate you must be at least 18 years old.\n\nWe look forward to welcoming you soon to one of our upcoming studies.\n'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'welcome_text', 'DE', 'Wir führen regelmässig wirtschaftswissenschaftliche Studien durch. Meist finden die Studien in einem Computerlabor statt, wo Sie an einem Computer sitzen und Fragen beantworten oder Entscheidungen zu gegebenen Situationen treffen. Darüberhinaus führen wir auch Studien mit anderen technischen Hilfsmitteln (bsp. FMRI, EEG) durch.\n\nWenn Sie sich bei uns registrieren und Ihr Account freigeschaltet wurde, erhalten Sie Einladungsemails mit Informationen zu aktuellen Studien. Nun können Sie selbst bestimmen, ob Sie gerne bei der betreffenden Studie mitmachen wollen. Die Studien werden anonym durchgeführt und nur für die wissenschaftliche Forschungsarbeit genutzt. Um an unseren Studien teilzunehmen, müssen Sie mindestens 18 Jahre alt sein.\n\nWir freuen uns Sie bald bei einer unserer Studien begrüssen zu dürfen.\n'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'password_policy_text', 'EN', 'The password must be at least 8 characters long, contain a number, a capital letter and a special character.'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'password_policy_text', 'DE', 'Das Passwort muss mindestens 8 Zeichen lang sein, eine Zahl, ein Grossbuchstabe und ein Sonderzeichen enthalten.'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'privacy_policy', 'EN', '<h1>Privacy policy</h1>'),
      (UNHEX(REPLACE(UUID(), '-', '')), 'privacy_policy', 'DE', '<h1>Datenschutzerklärung</h1>')
      ON DUPLICATE KEY UPDATE id = id;
  |sql}
;;

let migration_root () =
  Database.Migration.(
    empty "202309261013"
    |> add_step seed_root_default_message_templates
    |> add_step add_root_i18n_unique_constraint
    |> add_step seed_root_default_i18n)
;;
