version: "3.7"

services:
  app:
    image: "${DOCKER_IMAGE_URL}:${VERSION}"
    networks: [webgateway]
    environment:
      - CHECK_CSRF
      - DATABASE_URL
      - EMAIL_BYPASS_INTERCEPT
      - GITLAB_API_BASE
      - GITLAB_PROJECT_ID
      - GITLAB_PROJECT_NAME
      - GITLAB_TOKEN
      - PREFIX_PATH
      - PUBLIC_URL
      - QUEUE_FORCE_ASYNC
      - SIHL_ENV
      - SIHL_SECRET
      - SMTP_HOST
      - SMTP_PASSWORD
      - SMTP_PORT
      - SMTP_SECURE
      - SMTP_SENDER
      - SMTP_START_TLS
      - SMTP_USERNAME
      - TEST_EMAIL
      - VERSION
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.port=3000"
        - "traefik.docker.network=webgateway"
        # TODO: Move to other place in production (ECON only settings)
        - "traefik.pool.frontend.rule=Host:pool.econ.uzh.ch;PathPrefix:/staging/"
        - "traefik.pool-root.frontend.rule=Host:pool-root.econ.uzh.ch;PathPrefix:/staging/"
        - "traefik.tenant.frontend.rule=Host:tenant.econ.uzh.ch;PathPrefix:/staging/"

networks:
  webgateway:
    driver: overlay
    external: true
